name: AWS Batch Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  awsbatch:
    runs-on: "linux.20_04.4x"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Checkout TorchX
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: us-west-1
          role-to-assume: ${{ secrets.TF_AWS_ROLE_ARN }}
          role-session-name: github-torchx
        continue-on-error: true
      - name: Configure Docker
        run: |
          set -eux
          aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 495572122715.dkr.ecr.us-west-1.amazonaws.com
        continue-on-error: true
      - name: Install dependencies
        run: |
          set -eux
          pip install -e .[dev]
      - name: Run AWS Batch Integration Tests
        env:
          AWS_ROLE_ARN: ${{ secrets.TF_AWS_ROLE_ARN }}
        run: |
          set -ex

          scripts/awsbatchint.sh
